### ISSUE TITLE
instantly balance check

### ISSUE THREAD

**Issue by amirofski** [MrFreeDragon/VisualBTC#1]
change input background color to green when address have balance
or show address balance in page
https://blockchain.info/q/addressbalance/
https://www.npmjs.com/package/bitcoin-address-checker

**Comment by MrFreeDragon** [comment]
Can you please describe the reason to add balance check?

The idea of my tool was to create own bitcoin addresses but not to crack others.
Morover, i beleive that this feature will be useless as in almost 100% cases the generated addresses will have 0 balances. I also recommend to use my tool offline, so balance check will be not possible.

**Comment by MrFreeDragon** [comment]
I made some updates in my tool (added new features), and also added the balance check as you requested. Actually not the balance, but the total bolume of received transactions (which is the indicator that the address was used before).
The online check option is disabled by default but it could be turned on in advanced options.

The officail website is updated as well as the code on github.
