### ISSUE TITLE
Range selector

### ISSUE THREAD

**Issue by mattsmattsmatts** [MrFreeDragon/VisualBTC#2]
Can you add like a range selector, say I want to generate just 1st 2 rows at the bottom every time I hit random button, then I can change it to generate 1st 5 rows at the bottom only, etc. Would be a nice add on feature. Thanks.

**Comment by MrFreeDragon** [comment]
Do you mean the bit length of the private key?
By default it is 256bit (all cells are available), but you are asking to limit it and make the private keys with smaller bits (i.e. first 2 bottom lines only is 32bit key).

**Comment by mattsmattsmatts** [comment]
Yea, like select row 15 and 16, and when you press random key button, it
would only randomly generate blocks for those 2 rows only, which would
generate a low digit random key. You could also do so for columns and vise
versa.

**Comment by MrFreeDragon** [comment]
I have updated the tool. Added some new features, and also realized your request.  You should tick the box near "Block lines" in advanced options, and will be able to block lines from changing. The remaining lines will be ised for private key generation (as by user, so by Random feature of the tool).

The official website is updated as well as the code on github

**Comment by mattsmattsmatts** [comment]
Excellent work MrFreeDragon. Thanks a bunch.
