### ISSUE TITLE
For ETH

### ISSUE THREAD

**Issue by Isitsmd** [MrFreeDragon/VisualBTC#3]
Is it possible for Eth

**Comment by MrFreeDragon** [comment]
Yes, it is possible to create the same tool for ETH as well.
The Elliptic Curve part is the same (public keys are equal), but some  changes should be made for final address creation process.

And the pair private key / address would be the same for ETH, BSC, Polygon (Matic), etc

**Comment by Isitsmd** [comment]
Ohh
