### ISSUE TITLE
Could i find every private key with this script?

### ISSUE THREAD

**Issue by WHYYTE674** [MrFreeDragon/VisualBTC#4]
could i guess the pattern of every wallet ? even if it not created in this visualizer? finding the correct hex?

**Comment by MrFreeDragon** [comment]
Yes, if someone created the visual private key and you guess the same visual pattern you would receive exactly the same private key / bitcoin address pair.

**Comment by WHYYTE674** [comment]
And if someone does mot created it visual just in zhe wallet, could i guess it too? Legecy address when it was not created with the visual tool?

**Comment by MrFreeDragon** [comment]
The algorithm is the same. So it does not matter where you create the wallet, the same private key will lead to the same bitcoin address.
